/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controladores.ObraJpaController;
import controladores.PuntuacionJpaController;
import controladores.UsuarioJpaController;
import controladores.exceptions.NonexistentEntityException;
import entidades.Obra;
import entidades.Puntuacion;
import entidades.Usuario;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;

/**
 *
 * @author 34616
 */
public class GestionPuntuaciones extends javax.swing.JFrame {

    private static UsuarioJpaController ujc;
    private static ObraJpaController ojc;
    private static PuntuacionJpaController pjc;

    public GestionPuntuaciones() {
        ujc = new UsuarioJpaController(Persistence.createEntityManagerFactory("artebd"));
        ojc = new ObraJpaController(Persistence.createEntityManagerFactory("artebd"));
        pjc = new PuntuacionJpaController(Persistence.createEntityManagerFactory("artebd"));
        initComponents();
        String listaToString = "Codigo\t Nombre \t Autor \t Descripcion \t Año \t Categoría \n";
        List<Obra> lista = ojc.findObraEntities();
        for (Obra o : lista) {
            listaToString += o.toString();
        }

        tabla.setText(listaToString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTextArea();
        puntuacion = new javax.swing.JLabel();
        puntuacionInsert = new javax.swing.JTextField();
        comentario = new javax.swing.JLabel();
        comentarioInsert = new javax.swing.JTextField();
        codPuntuacion = new javax.swing.JLabel();
        codPuntuacionInsert = new javax.swing.JTextField();
        codObra = new javax.swing.JLabel();
        codObraInsert = new javax.swing.JTextField();
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(165, 1, 17));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titulo.setText("Puntuación");
        panelFondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 70));

        tabla.setEditable(false);
        tabla.setColumns(20);
        tabla.setRows(5);
        jScrollPane1.setViewportView(tabla);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 800, 290));

        puntuacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        puntuacion.setForeground(new java.awt.Color(230, 123, 133));
        puntuacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        puntuacion.setText("Puntuación");
        panelFondo.add(puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 130, 30));

        puntuacionInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntuacionInsertActionPerformed(evt);
            }
        });
        panelFondo.add(puntuacionInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 280, 30));

        comentario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comentario.setForeground(new java.awt.Color(230, 123, 133));
        comentario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        comentario.setText("Comentario");
        panelFondo.add(comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 140, 30));

        comentarioInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentarioInsertActionPerformed(evt);
            }
        });
        panelFondo.add(comentarioInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 280, 30));

        codPuntuacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        codPuntuacion.setForeground(new java.awt.Color(230, 123, 133));
        codPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codPuntuacion.setText("Código puntuacion");
        panelFondo.add(codPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 180, 30));

        codPuntuacionInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPuntuacionInsertActionPerformed(evt);
            }
        });
        panelFondo.add(codPuntuacionInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 60, 30));

        codObra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        codObra.setForeground(new java.awt.Color(230, 123, 133));
        codObra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codObra.setText("Código obra");
        panelFondo.add(codObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 180, 30));

        codObraInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codObraInsertActionPerformed(evt);
            }
        });
        panelFondo.add(codObraInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 60, 30));

        insertar.setBackground(new java.awt.Color(217, 135, 143));
        insertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertar.setForeground(new java.awt.Color(255, 255, 255));
        insertar.setText("Insertar");
        insertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        panelFondo.add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 100, 30));

        eliminar.setBackground(new java.awt.Color(217, 135, 143));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        panelFondo.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 100, 30));

        actualizar.setBackground(new java.awt.Color(217, 135, 143));
        actualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar");
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        panelFondo.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 100, 30));

        info.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        info.setForeground(new java.awt.Color(103, 181, 181));
        panelFondo.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 390, 30));

        atras.setBackground(new java.awt.Color(217, 135, 143));
        atras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        panelFondo.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 100, 30));

        imagenFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\FX506\\Documents\\NetBeansProjects\\ejersRecuProg\\ProyectoFinalNoeliaP\\src\\main\\resources\\fotos\\menu2.jpeg")); // NOI18N
        imagenFondo.setText("jLabel1");
        panelFondo.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntuacionInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntuacionInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntuacionInsertActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        pjc.create(new Puntuacion(Integer.valueOf(puntuacionInsert.getText()), comentarioInsert.getText(), new Obra(Integer.valueOf(codObraInsert.getText()))));
        puntuacionInsert.setText("");
        comentarioInsert.setText("");
        codObraInsert.setText("");
        info.setText("Puntuación introducida correctamente");
        String listaToString = "Codigo\t Obra \t Puntuacion \t Comentario \n";
        List<Puntuacion> lista = pjc.findPuntuacionEntities();
        for (Puntuacion p : lista) {
            listaToString += p.toString();
        }

        tabla.setText(listaToString);
    }//GEN-LAST:event_insertarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed

        try {
            pjc.destroy(Integer.valueOf(codPuntuacionInsert.getText()));
            info.setText("Puntuacion con codigo " + codPuntuacionInsert.getText() + " eliminado correctamente");
        } catch (NonexistentEntityException ex) {
            info.setText("Codigo erroneo, introduzca un codigo valido");
        }
        codPuntuacionInsert.setText("");
        String listaToString = "Codigo\t Obra \t Puntuacion \t Comentario \n";
        List<Puntuacion> lista = pjc.findPuntuacionEntities();
        for (Puntuacion p : lista) {
            listaToString += p.toString();
        }

        tabla.setText(listaToString);
    }//GEN-LAST:event_eliminarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            Puntuacion p=pjc.findPuntuacion(Integer.valueOf(codPuntuacionInsert.getText()));
            pjc.edit(new Puntuacion(p.getIdpuntu(), Integer.valueOf(puntuacionInsert.getText()), comentarioInsert.getText(), p.getObraId()));
            info.setText("Obra con codigo " + codObraInsert.getText() + " modificada correctamente");
        } catch (Exception ex) {
            info.setText("Codigo erroneo, introduzca un codigo valido");
        }
        codPuntuacionInsert.setText("");
        puntuacionInsert.setText("");
        comentarioInsert.setText("");
        codObraInsert.setText("");
        String listaToString = "Codigo\t Obra \t Puntuacion \t Comentario \n";
        List<Puntuacion> lista = pjc.findPuntuacionEntities();
        for (Puntuacion p : lista) {
            listaToString += p.toString();
        }

        tabla.setText(listaToString);
    }//GEN-LAST:event_actualizarActionPerformed

    private void codPuntuacionInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codPuntuacionInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codPuntuacionInsertActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        VentanaPrincipal v = new VentanaPrincipal();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void comentarioInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentarioInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comentarioInsertActionPerformed

    private void codObraInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codObraInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codObraInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPuntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPuntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPuntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPuntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionPuntuaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton atras;
    private javax.swing.JLabel codObra;
    private javax.swing.JTextField codObraInsert;
    private javax.swing.JLabel codPuntuacion;
    private javax.swing.JTextField codPuntuacionInsert;
    private javax.swing.JLabel comentario;
    private javax.swing.JTextField comentarioInsert;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel info;
    private javax.swing.JButton insertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel puntuacion;
    private javax.swing.JTextField puntuacionInsert;
    private javax.swing.JTextArea tabla;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
